<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.9.4" xml:lang="en-US">
  <compounddef id="classException" kind="class" language="Python" prot="public">
    <compoundname>Exception</compoundname>
    <derivedcompoundref refid="classpenify__hook_1_1utils_1_1GitRepoNotFoundError" prot="public" virt="non-virtual">penify_hook.utils.GitRepoNotFoundError</derivedcompoundref>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="1">
        <label>Exception</label>
        <link refid="classException"/>
      </node>
      <node id="2">
        <label>penify_hook.utils.GitRepoNotFoundError</label>
        <link refid="classpenify__hook_1_1utils_1_1GitRepoNotFoundError"/>
        <childnode refid="1" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="1">
        <label>Exception</label>
        <link refid="classException"/>
      </node>
    </collaborationgraph>
    <location file="/tmp/github_reposRepoArchDocGenContext/Penify-dev/penify-cli/penify_hook/utils.py" line="9" column="1"/>
    <listofallmembers>
    </listofallmembers>
  </compounddef>
</doxygen>
